#!/usr/bin/env python3
"""Export elliptic-factor diagnostics for the EP885 fifth-column curve.

For fixed rows N_1,...,N_4, the quotient of the fifth-column curve is

    C: y_i^2 = t + N_i,  i=1..4.

Its Jacobian decomposes into elliptic factors attached to the four triple
products and the one quartic product:

    z^2 = prod_{i in S} (t + N_i),  |S| = 3 or 4.

This script exports Sage code for a Bremner seed so that rank, generators,
known old-column points, and Chabauty/sieve checks can be run in Sage/Magma.
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import bremner_map


def parse_ints(spec: str | None) -> list[int]:
    if not spec:
        return []
    return [int(x.strip()) for x in spec.replace("\n", ",").split(",") if x.strip()]


def poly_product_linear(constants: list[int]) -> list[int]:
    """Return coefficients of prod(t + c), low-to-high."""
    coeffs = [1]
    for c in constants:
        nxt = [0] * (len(coeffs) + 1)
        for i, coeff in enumerate(coeffs):
            nxt[i] += coeff * c
            nxt[i + 1] += coeff
        coeffs = nxt
    return coeffs


def sage_poly(coeffs: list[int]) -> str:
    terms = []
    for power, coeff in enumerate(coeffs):
        if coeff == 0:
            continue
        if power == 0:
            monomial = "1"
        elif power == 1:
            monomial = "t"
        else:
            monomial = f"t^{power}"
        terms.append(f"({coeff})*{monomial}")
    return " + ".join(terms) if terms else "0"


def make_sage(seed_label: str, n_values: list[int], deltas: list[int]) -> str:
    old_t_values = [(d // 2) ** 2 for d in deltas]
    triples = list(itertools.combinations(range(4), 3))
    quartic_pivot = 3
    other = [i for i in range(4) if i != quartic_pivot]
    q_deltas = [n_values[i] - n_values[quartic_pivot] for i in other]
    q_a = q_deltas[0] * q_deltas[1] * q_deltas[2]
    q_b = q_deltas[0] * q_deltas[1] + q_deltas[0] * q_deltas[2] + q_deltas[1] * q_deltas[2]
    q_c = q_deltas[0] + q_deltas[1] + q_deltas[2]
    lines = [
        "# Auto-generated by scripts/elliptic_factor_export.py",
        f"# Seed: {seed_label}",
        "QQ = RationalField()",
        "R.<t> = PolynomialRing(QQ)",
        f"N = {n_values}",
        f"old_t = {old_t_values}",
        "",
        "def safe_rank_bounds(E):",
        "    try:",
        "        return E.rank_bounds()",
        "    except Exception as err:",
        "        return 'rank_bounds failed: %s' % err",
        "",
        "def safe_gens(E):",
        "    try:",
        "        return E.gens()",
        "    except Exception as err:",
        "        return 'gens failed: %s' % err",
        "",
        "factors = []",
    ]
    for indices in triples:
        p, q, r = indices
        label = "".join(str(i + 1) for i in indices)
        A = (n_values[q] - n_values[p]) + (n_values[r] - n_values[p])
        B = (n_values[q] - n_values[p]) * (n_values[r] - n_values[p])
        known_points = []
        for old_t in old_t_values:
            y = 1
            for i in indices:
                value = old_t + n_values[i]
                root = math.isqrt(value)
                if root * root != value:
                    raise ValueError(f"old point is not square for factor {label}")
                y *= root
            known_points.append((old_t + n_values[p], y))
        lines.extend(
            [
                f"E_{label} = EllipticCurve(QQ, [0, {A}, 0, {B}, 0])",
                f"known_{label} = {known_points}",
                f"print('factor {label}: triple pivot {p + 1}')",
                f"print('  E =', E_{label})",
                f"print('  minimal =', E_{label}.global_minimal_model())",
                f"print('  rank bounds =', safe_rank_bounds(E_{label}))",
                f"print('  torsion =', E_{label}.torsion_subgroup())",
                f"print('  known points =', [E_{label}(P) for P in known_{label}])",
                f"print('  known generated rank <=', len(E_{label}.saturation([E_{label}(P) for P in known_{label}])[0]))",
                "",
            ]
        )
    q_known_points = []
    for old_t in old_t_values:
        den = old_t + n_values[quartic_pivot]
        yprod = 1
        for i in range(4):
            value = old_t + n_values[i]
            root = math.isqrt(value)
            if root * root != value:
                raise ValueError("old point is not square for quartic factor")
            yprod *= root
        q_known_points.append((f"QQ({q_a})/QQ({den})", f"QQ({q_a})*QQ({yprod})/(QQ({den})^2)"))
    lines.extend(
        [
            f"E_1234 = EllipticCurve(QQ, [0, {q_b}, 0, {q_a * q_c}, {q_a * q_a}])",
            "known_1234 = [" + ", ".join("(%s, %s)" % p for p in q_known_points) + "]",
            "print('factor 1234: quartic pivot 4')",
            "print('  E =', E_1234)",
            "print('  minimal =', E_1234.global_minimal_model())",
            "print('  rank bounds =', safe_rank_bounds(E_1234))",
            "print('  torsion =', E_1234.torsion_subgroup())",
            "print('  known points =', [E_1234(P) for P in known_1234])",
            "print('  known generated rank <=', len(E_1234.saturation([E_1234(P) for P in known_1234])[0]))",
            "",
        ]
    )
    lines.extend(
        [
            "print('old t-values:')",
            "for T in old_t:",
            "    vals = [T + n for n in N]",
            "    print(T, vals)",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int)
    parser.add_argument("--torsion", action="store_true")
    parser.add_argument("--label", default="custom")
    parser.add_argument("--n-values", help="Comma-separated row values for a custom seed.")
    parser.add_argument("--deltas", help="Comma-separated deltas for a custom seed.")
    parser.add_argument("--out-json", type=Path)
    parser.add_argument("--out-sage", type=Path, required=True)
    args = parser.parse_args()

    custom_ns = parse_ints(args.n_values)
    custom_deltas = parse_ints(args.deltas)
    if custom_ns:
        if len(custom_ns) != 4 or len(custom_deltas) != 4:
            raise SystemExit("custom elliptic-factor export expects exactly four N values and four deltas")
        n_values = custom_ns
        deltas = custom_deltas
        label = args.label
    else:
        if args.n is None:
            raise SystemExit("provide either --n or --n-values/--deltas")
        seed = bremner_map.generate(args.n, args.torsion)
        n_values = seed.N_values
        deltas = seed.deltas
        label = f"{args.n}Q+T" if args.torsion else f"{args.n}Q"
    payload = {
        "seed": label,
        "deltas": deltas,
        "old_t_values": [(d // 2) ** 2 for d in deltas],
        "N_values": n_values,
    }
    args.out_sage.parent.mkdir(parents=True, exist_ok=True)
    args.out_sage.write_text(make_sage(label, n_values, deltas), encoding="utf-8")
    if args.out_json:
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
