#!/usr/bin/env python3
"""Export Magma workflow for EP885 fifth-column compatibility curves."""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import bremner_map


def parse_ints(spec: str | None) -> list[int]:
    if not spec:
        return []
    return [int(x.strip()) for x in spec.replace("\n", ",").split(",") if x.strip()]


def roots_for_old_columns(n_values: list[int], deltas: list[int]) -> list[list[int]]:
    rows: list[list[int]] = []
    for d in deltas:
        t = (d // 2) ** 2
        roots = []
        for n in n_values:
            value = t + n
            root = math.isqrt(value)
            if root * root != value:
                raise ValueError(f"not square: {t}+{n}")
            roots.append(root)
        rows.append(roots)
    return rows


def magma_sequence(values: list[int]) -> str:
    return "[ " + ", ".join(str(v) for v in values) + " ]"


def magma_matrix(rows: list[list[int]]) -> str:
    return "[ " + ",\n    ".join(magma_sequence(row) for row in rows) + " ]"


def make_magma(seed_label: str, n_values: list[int], deltas: list[int]) -> str:
    old_t = [(d // 2) ** 2 for d in deltas]
    yold = roots_for_old_columns(n_values, deltas)
    return f"""// Auto-generated by scripts/magma_compatibility_export.py
// Seed: {seed_label}

Q := Rationals();
N := [ Q | {', '.join(str(v) for v in n_values)} ];
told := [ Q | {', '.join(str(v) for v in old_t)} ];
yold := [
    {',\n    '.join('[ Q | ' + ', '.join(str(v) for v in row) + ' ]' for row in yold)}
];

for j in [1..#told] do
    for i in [1..4] do
        assert yold[j][i]^2 eq told[j] + N[i];
    end for;
end for;

function TripleElliptic(N, I)
    p := I[1]; q := I[2]; r := I[3];
    A := (N[q]-N[p]) + (N[r]-N[p]);
    B := (N[q]-N[p])*(N[r]-N[p]);
    E := EllipticCurve([ Q | 0, A, 0, B, 0 ]);
    return E, p;
end function;

function QuarticElliptic(N, p)
    J := [ i : i in [1..4] | i ne p ];
    d1 := N[J[1]] - N[p];
    d2 := N[J[2]] - N[p];
    d3 := N[J[3]] - N[p];
    a := d1*d2*d3;
    b := d1*d2 + d1*d3 + d2*d3;
    c := d1 + d2 + d3;
    E := EllipticCurve([ Q | 0, b, 0, a*c, a^2 ]);
    return E, p, a;
end function;

function TripleImage(N, I, E, piv, tval, yvec)
    X := tval + N[piv];
    Y := &*[ yvec[i] : i in I ];
    return E![X, Y, 1];
end function;

function QuarticImage(N, E, piv, a, tval, yvec)
    den := tval + N[piv];
    assert den ne 0;
    X := a/den;
    Y := a*(&*yvec)/(den^2);
    return E![X, Y, 1];
end function;

function CompatibilityCurve(N, m)
    R<W> := PolynomialRing(Q);
    I := [ i : i in [1..4] | i ne m ];
    f := &*[ W^2 + N[i] - N[m] : i in I ];
    D := HyperellipticCurve(f);
    return D, I, f;
end function;

function SquareRational(x)
    ok, root := IsSquare(x);
    return ok, root;
end function;

function LiftsToC(N, m, Wval)
    tval := Wval^2 - N[m];
    ys := [];
    for i in [1..4] do
        ok, y := IsSquare(tval + N[i]);
        if not ok then
            return false, _, _;
        end if;
        Append(~ys, y);
    end for;
    return true, tval, ys;
end function;

Triples := [
    [1,2,3],
    [1,2,4],
    [1,3,4],
    [2,3,4]
];

TripleData := [];
for I in Triples do
    E, piv := TripleElliptic(N, I);
    Append(~TripleData, <I, E, piv>);
    print "Triple", I;
    print MinimalModel(E);
    print "Rank bounds:", RankBounds(E);
    print "Torsion:", TorsionSubgroup(E);
    print "Old images:";
    for j in [1..#told] do
        P := TripleImage(N, I, E, piv, told[j], yold[j]);
        print j, P;
    end for;
end for;

E4, piv4, a4 := QuarticElliptic(N, 4);
print "Quartic factor";
print MinimalModel(E4);
print "Rank bounds:", RankBounds(E4);
print "Torsion:", TorsionSubgroup(E4);
print "Old images:";
for j in [1..#told] do
    P := QuarticImage(N, E4, piv4, a4, told[j], yold[j]);
    print j, P;
end for;

for m in [1..4] do
    D, I, f := CompatibilityCurve(N, m);
    print "Compatibility D_m", m, "I", I;
    print "f =", f;
    print "Genus", Genus(D);
    J := Jacobian(D);
    try
        print "RankBound Jac(D):", RankBound(J);
    catch err
        print "RankBound failed:", err;
    end try;
    print "Small points search";
    try
        pts := Points(D : Bound := 10000);
        print pts;
        for P in pts do
            if P[3] ne 0 then
                Wval := P[1]/P[3];
                okC, tval, ys := LiftsToC(N, m, Wval);
                if okC then
                    okSquare, X := IsSquare(tval);
                    print "  lifts to C", P, "t", tval, "t square?", okSquare;
                end if;
            end if;
        end for;
    catch err
        print "Points search failed:", err;
    end try;
end for;
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int)
    parser.add_argument("--torsion", action="store_true")
    parser.add_argument("--label", default="custom")
    parser.add_argument("--n-values", help="Comma-separated row values for a custom seed.")
    parser.add_argument("--deltas", help="Comma-separated deltas for a custom seed.")
    parser.add_argument("--out-magma", type=Path, required=True)
    parser.add_argument("--out-json", type=Path)
    args = parser.parse_args()

    custom_ns = parse_ints(args.n_values)
    custom_deltas = parse_ints(args.deltas)
    if custom_ns:
        if len(custom_ns) != 4 or len(custom_deltas) != 4:
            raise SystemExit("custom Magma compatibility export expects exactly four N values and four deltas")
        n_values = custom_ns
        deltas = custom_deltas
        label = args.label
    else:
        if args.n is None:
            raise SystemExit("provide either --n or --n-values/--deltas")
        seed = bremner_map.generate(args.n, args.torsion)
        n_values = seed.N_values
        deltas = seed.deltas
        label = f"{args.n}Q+T" if args.torsion else f"{args.n}Q"
    payload = {
        "seed": label,
        "deltas": deltas,
        "old_t_values": [(d // 2) ** 2 for d in deltas],
        "N_values": n_values,
        "yold": roots_for_old_columns(n_values, deltas),
    }
    args.out_magma.parent.mkdir(parents=True, exist_ok=True)
    args.out_magma.write_text(make_magma(label, n_values, deltas), encoding="utf-8")
    if args.out_json:
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
